### ISSUE TITLE
How to tell the login to use an old SHA1 encrypted by username+password ?

### ISSUE THREAD

**Issue by broxinagil** [migratetoflarum/old-passwords#2]
Top Extension, very usefull for migrating old Forums btw.
As it is known, Simplemachines Forum (SMF) uses sha1(username+password) for pw encryption. How do I advise this Extension to use that encrypted pw ?

**Comment by broxinagil** [comment]
Ah, seems I can use "salt-before" with the username to do so ?

**Comment by clarkwinkelmann** [comment]
Yep, seems like `salt-before` would do the trick. Were you able to confirm it works ?

**Comment by broxinagil** [comment]
Not yet. Will check this within the next days and report

**Comment by clarkwinkelmann** [comment]
I'm closing the issue, feel free to respond/reopen it if you need further help :wink:
